# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181023_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='skills',
        ),
        migrations.AddField(
            model_name='position',
            name='skill',
            field=models.CharField(choices=[('Android', 'Android Developer'), ('Design', 'Designer'), ('Java', 'Java Developer'), ('PHP', 'PHP Developer'), ('Python', 'Python Developer'), ('Rails', 'Rails Developer'), ('Wordpress', 'Wordpress Developer'), ('iOS', 'iOS Developer')], default='', max_length=20),
        ),
    ]
