# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181024_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Project'),
        ),
    ]
