# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_position_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='timeline',
            new_name='estimated_time',
        ),
    ]
