# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_position_filled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
