# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 00:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_auto_20181113_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='applicants',
            field=models.ManyToManyField(through='projects.Application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='position',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='projects.Project'),
        ),
    ]
