# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20181116_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='applicants',
        ),
    ]
