# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20181127_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='skill',
            field=models.CharField(choices=[('Android', 'Android Developer'), ('Design', 'Designer'), ('Java', 'Java Developer'), ('PHP', 'PHP Developer'), ('Python', 'Python Developer'), ('Rails', 'Rails Developer'), ('Wordpress', 'Wordpress Developer'), ('iOS', 'iOS Developer')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
