# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-27 19:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20181127_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicaion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Position'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Application'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='position',
            name='skill',
            field=models.CharField(blank=True, choices=[('Android', 'Android Developer'), ('Design', 'Designer'), ('Java', 'Java Developer'), ('PHP', 'PHP Developer'), ('Python', 'Python Developer'), ('Rails', 'Rails Developer'), ('Wordpress', 'Wordpress Developer'), ('iOS', 'iOS Developer')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
